window.GA_ID = window.GA_ID || "%GA_ID%";
window.RECAPTCHA_SITE_KEY = window.RECAPTCHA_SITE_KEY || "%RECAPTCHA_SITE_KEY%";
window.PHONE_NUMBER = window.PHONE_NUMBER || "%PHONE_NUMBER%";
window.SUBSCRIBE_ENDPOINT = window.SUBSCRIBE_ENDPOINT || "%SUBSCRIBE_ENDPOINT%";
