name: Update sold items

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install and update sold items
        env:
          EBAY_APP_ID: ${{ secrets.EBAY_APP_ID }}
        run: npm ci && npm run update-sold
      - name: Run tests
        run: npm test
      - name: Commit and push if sold items changed
        if: success()
        run: |
          if [ -n "$(git status --porcelain sold-items.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add sold-items.json
            git commit -m "chore: update sold items"
            git push
          fi
